package sidewinder.client;

/**
 * Typed structural interface for async clients generated by AutoClientAsync.createWithOptions.
 * Each instantiation AsyncClient<IFoo> is resolved at compile time via @:genericBuild,
 * producing a TAnonymous structural type from IFoo's HTTP-annotated methods.
 *
 * The generated impl class satisfies this structural type without any cast — Haxe's
 * structural typing handles the assignment safely on all targets including HashLink.
 *
 * Usage:
 *   var svc:AsyncClient<IMyService> = AutoClientAsync.createWithOptions(IMyService, opts);
 *   svc.doThingAsync(arg, (result) -> trace(result), (err) -> trace(err));
 *   svc.options.token = newToken;
 */
#if !macro
@:genericBuild(sidewinder.client.AutoClientAsync.buildAsyncClient())
class AsyncClient<T> {}
#end
